---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __K8S_APP_NAME__
  labels:
    app: __K8S_APP_NAME__
spec:
  selector:
    matchLabels:
      app: __K8S_APP_NAME__
  template:
    metadata:
      labels:
        app: __K8S_APP_NAME__
    spec:
      containers:
      - name: __K8S_APP_NAME__
        image: __REPOSITORY_IMAGE_NAME__
        volumeMounts:
        - name: __KeyVaultName__-flexvolume
          mountPath: /kvmnt
          readOnly: true
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: __K8S_APP_NAME__-configmap
      volumes:
      - name: __KEY_VAULT_NAME__-flexvolume
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: __KEY_VAULT_SECRET_NAME__ # reference the service principal kubernetes secret
          options:
            usepodidentity: "false"                            # [OPTIONAL] if not provided, will default to "false"
            keyvaultname: "__KEY_VAULT_NAME__"                 # the name of the KeyVault
            keyvaultobjectnames: "__KEY_VAULT_OBJECT_NAMES__"  # list of KeyVault object names (semi-colon separated)
            keyvaultobjecttypes: __KEY_VAULT_OBJECT_TYPES__    # list of KeyVault object types: secret, key or cert (semi-colon separated)
            keyvaultobjectversions: ""                         # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
            resourcegroup: "__KEY_VAULT_RG_NAME__"             # the resource group of the KeyVault        
            subscriptionid: "__SUBSCRIPTION_ID__"              # the subscription ID of the KeyVault
            tenantid: "__TENANT_ID__"                          # the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: __K8S_APP_NAME__
  labels:
    app: __K8S_APP_NAME__
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: __K8S_APP_NAME__
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: __K8S_APP_NAME__-hpa
  labels:
    app: __K8S_APP_NAME__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: __K8S_APP_NAME__
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80 
  